### PR TITLE
Possible Merge.

### PR DESCRIPTION
**Pull request by psyciknz**
I changed the main name of the script so that it could integrate with travis-ci and docker hub.

I currently post this image on dockerhub as psyciknz/paradoxip

As far as I can tell most of the changes seem to be compatible.  There's been a couple of little fixes gong in (SP specific).

I've also been looking at the https://github.com/jpbarraca/pai -  which may have advantages for newer firmware....but I'm happy with what here.   Though one cool feature they have is setting the clock time from the source machine...and an interface that allows external access though their service (since I never find the polling disconnect to work.

While I'm mostly happy if you want to deny, unsure if you want to carry on.

### CODE REVIEW

**Comment by Tertiush** [comment]
Thanks for this, but can I propose an alternative... The code currently works perfectly fine for my use-case and may serve as a reference for others. Seeing as I'm not actively contributing to it anymore I think its best to rather make mention of the other projects and link to them from mine. That way you can better support your initiatives on GH with users logging issues to your rather than my repository. Your thoughts?

**Comment by psyciknz** [comment]
So essentially park your fork as you’re happy with it and it’s current feature set and start firing new people towards mine and/or jpbarraca?

That’s fine by me.  I know you have left it for annit, but then came back so was unsure if you were interested in continuing contributions.

**Comment by Tertiush** [comment]
That's exactly it yes - I really don't have the time to take it further. I'll add a link to your profile from the readme.

**Comment by psyciknz** [comment]
Leaving Forks separate

**Pull request closed without merging**
