### PR TITLE
Reading initial state, bugfix, small enchancements...

### PR DESCRIPTION
**Pull request by 9a4gl**
This should 
1. do initial state reading and publishing
  https://github.com/Tertiush/ParadoxIP150v2/issues/6
2. fix publishing zone change with zone name containing space
3. publish timestamp with some messages
...

### CODE REVIEW

**Comment by Tertiush** [comment]
Thanks for the PR!! I assume you have tested the code, I unfortunately won't have a chance anytime soon to do so, but am happy to merge if you haven't had any issues to date....?

**Comment by 9a4gl** [comment]
I did, but with 5050 unit. Hope there will not be issues with other. In worst case if it cause issue revert it later :)

**Comment by cybertza** [comment]
The publish with timestamp should be an config.ini enable disable function.
It is a breaking change for any integration that is looking for an zone to be 
"ON"
is now receiving
"ON 154831564"

Net result is 

2018-02-18 21:50:35 WARNING (MainThread) [homeassistant.components.binary_sensor.mqtt] No matching payload found for entity: Passage with state_topic: Paradox/Zone/PASSAGE
2018-02-18 21:50:35 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1518983435.948583, level=WARNING, message=No matching payload found for entity: Passage with state_topic: Paradox/Zone/PASSAGE, exception=, source=components/binary_sensor/mqtt.py>
2018-02-18 21:50:38 WARNING (MainThread) [homeassistant.components.binary_sensor.mqtt] No matching payload found for entity: Passage with state_topic: Paradox/Zone/PASSAGE
2018-02-18 21:50:38 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1518983438.0033672, level=WARNING, message=No matching payload found for entity: Passage with state_topic: Paradox/Zone/PASSAGE, exception=, source=components/binary_sensor/mqtt.py>

Payload looks like this:
2/18/2018, 9:50:44 PMnode: 81aefd7.37b08
Paradox/Zone/PASSAGE : msg.payload : string[13]
"ON 1518983435"
2/18/2018, 9:50:46 PMnode: 81aefd7.37b08
Paradox/Zone/PASSAGE : msg.payload : string[14]
"OFF 1518983438"

**Comment by 9a4gl** [comment]
I agree, can you fix it ? I will not be able to do that next few days.

**Comment by psyciknz** [comment]
I'm working on a fix for the timestamp, I think I've updated my fork with it, but I think I've just removed the publishwithtimestamp call with a straight publish.

I've also been working on trying to understand  the SP protocol more, but hitting a brick wall, as I'm not getting the responses back that I expect to see.

**Pull request merged**
